### ISSUE TITLE
nozzle crashes after running only a few minutes

### ISSUE THREAD

**Issue by cholick** [mcplusa/cloudfoundry-sumologic-nozzle#11]
```
panic: interface conversion: interface is string, not int64

goroutine 10 [running]:
panic(0x3cdf80, 0xc420208140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose.StringBuilder(0xc4202741e0, 0xc420311100, 0x437488, 0x0, 0x437488, 0x0, 0x0, 0xe7)
	/Users/mcholick/go/src/github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose/sumoLogicAppender.go:170 +0x1034
github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose.(*SumoLogicAppender).AppendLogs(0xc4200d5b30, 0xc4204f3f60)
	/Users/mcholick/go/src/github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose/sumoLogicAppender.go:233 +0x82
github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose.(*SumoLogicAppender).Start(0xc4200d5b30)
	/Users/mcholick/go/src/github.com/mcplusa/cloudfoundry-sumologic-nozzle/sumoCFFirehose/sumoLogicAppender.go:105 +0x996
created by main.main
	/Users/mcholick/go/src/github.com/mcplusa/cloudfoundry-sumologic-nozzle/main.go:94 +0x147d
exit status 2
```

**Comment by cholick** [comment]
For this test, I was harvesting all the event types.

**Comment by sklava** [comment]
There was an issue with a timestamp.  Nicole fixed this. commit fd600bb61f8c1191e406e4bca751eecfc33fa075 @nmillalaf nmillalaf committed on Jan 13
